### ISSUE TITLE
hasContributor restrict domain

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/arche-schema#18]
currently the domain for `hasContributor` is set to p,c,r,m,pub,pl,o,pe which imho makes not much sense for pe, pl, o, because what should acdhi:brunokreisy hasContributor acdhi:maxmayer exactly mean?

therefore I suggest to restrict the domain of `hasContributor` to p,c,r,m,pub

**Comment by carlonim** [comment]
Yes, it doesn't make much sense. The only problem is that `hasContributor` has, among its various subproperties, also `hasMetadataCreator`. Since the domain of `hasMetadataCreator` is `Main` – which includes persons, places, and organizations too – the domain of its super-property `hasContributor` should also include these classes. This is probably why it was decided to assign domain `Main` to `hasContributor`.
Unfortunately, I'm afraid we can't do much to restrict its domain, unless we "move" `hasMetadataCreator` out of the sub-properties of `hasContributor`.
