### ISSUE TITLE
new properties `acdh:hasHeight` and `acdh:hasWidth`

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/arche-schema#32]
why:
* mainly for images; would be used for IIIF-Manifest creation
* currently I (would) write this information in acdh:hasExtent, but from there it can't be processed further

domain: `acdh:Resource`
range: integer?
cardinality: 0-1

**Comment by sstuhec** [comment]
If you need this for IIIF Manifest, it is ok for me. hasExtent anyhow does not really fit here, because it is also used for the content (e.g. number of objects) and hasHight/hasWidth is about the technical attribute of a digital file - so please make sure that the definition is clear in this regard, or even the property name hasImageHight/hasImageWidth or something in this sense, so people do not think this are the measurements of whatever is depicted on the image ;-).

**Comment by zozlak** [comment]
Introduced in [4.3.0](https://github.com/acdh-oeaw/arche-schema/releases/tag/v4.3.0) but:

* these property values should still be extracted and added for the existing data
* the arche-core needs to be modified to extract them automatically
