### ISSUE TITLE
allow `achd:hasUrl` for `acdh:Place`

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/arche-schema#36]
currently all ARCHE-Classes (Person, Collection, Resource, ...) except Place are allowed to have the property acdh:hasUrl

IMHO this should be changed

**Comment by bellerophons-pegasus** [comment]
The idea behind achd:hasUrl is to be able to include a link to a webpage for persons, projects or another (external) webpage representing a collection (e.g. a collections project page). We do have plenty of use cases for that. URLs attached via acdh:hasUrl might one day become invalid, which is why we are aiming to register the ones we get with the internet archive. 
In ARCHE we use instances of Place for geolocating a collection/resource etc. The information behind a place (coordinates and names) is usually stored in some authority file which we link via acdh:hasIdentifier
So I do think the status quo is fine. 

Please elaborate why acdh:hasUrl should be allowed for Place as well.

**Comment by csae8092** [comment]
in our static digital-editions set up places (as persons, institutions or resources like the HTML representation of letters, diary entries ...) do have their own website with information about the entity/resource as well as pointers to their related objects. due to the static set up, I'd consider those URLs very stable; so I'd like to use hasUrl to point from ARCHE-Resources their web-app detail views.

the added value for ARCHE-Users would be;
* they can get from ARCHE to the web-page the ARCHE resource is derived from
* users could spot very easily in which projects/web-resources a given entity, a given place is mentioned as well like e.g. PMB does this very nicely (https://pmb.acdh.oeaw.ac.at/apis/entities/entity/place/685/detail)

so the question would be; should I point from an acdh:Person to e.g. https://schnitzler-briefe.acdh.oeaw.ac.at/pmb2132.html and if so, than why not also from an acdh:Place to e.g. https://schnitzler-briefe.acdh.oeaw.ac.at/pmb685.html

**Comment by zozlak** [comment]
@bellerophons-pegasus it's almost a month since Peter's reply. Could you please state your opinion?

**Comment by bellerophons-pegasus** [comment]
Apologies.

Hmmm, in the given example `acdh:hasUrl` is not used for the person in ARCHE (checked production and curation).

As far as I recall we do allow using PMB IDs as an authority source for Actors, so I do think that PMB is fine to be used for places as well. 

Would that solve what you are trying to achieve?

**Comment by csae8092** [comment]
No, because I'd like to point via hasUrl to a website an not so some ID

**Comment by bellerophons-pegasus** [comment]
Okay, thanks.

I gave it some thought and I can't see any harm done with allowing `acdh:hasUrl` for `acdh:Place`.

@sstuhec and @uczeitschner do you have any objections? 
If not, please proceed. I think the description of `acdh:hasUrl` will also have to be updated.
