### ISSUE TITLE
Questions regarding Ontology V2

### ISSUE THREAD

**Issue by bellerophons-pegasus** [acdh-oeaw/arche-schema#4]
I finally have some time en bloc to work on the finalisation of V2 of the ontology.

Some questions arise, which I do not want to post into the already very long discussion in the pull 

1. acdh:hasAccessRestrcition: after some back and forth we came to the agreement, that it should only be used for binary content (i.e. entities of class Binary, Metadata or Image). Everything else, including Collection, is purely metadata and that is always public. For Collection we will have hasAccessRestrictionSummary which is going to be filled automatically depending on the children of the collection. 
**Question**: Are there any objections from the technical point of view to remove it from the class Collection?

2. Cardinalities (yet again). We had rather heated discussions about keeping or discarding cardinalities for properties that are automatically filled by the system or not. To summarise: Keep: OWL document which properties need to have a value in the end. Discard: It would make it more difficult for metadata creators and curators to distinguish which properties they must provide and which they don't 
A compromise was proposed: Keep the cardinalities for documenting somewhere which properties in the end need to have a value and in the root table also display which value is automatically filled.
**Question** (directly to @zozlak): is that a way to go? Then I would reintroduce the cardinalities.

**Comment by bellerophons-pegasus** [comment]
3. Why does PID minting automation now has to be triggered by the user with a proper - empty string - property value? Before, the user had to submit something like 'create me' in the property. I am already thinking of the Metadata Editor here, where an additional query has to be added in the code and some visual element has to be included in the form, in order to properly allow the user to either not create a PID or automatically create one.

**Comment by bellerophons-pegasus** [comment]
4. Why does a qualified restriction like ''has updated date' max 1 xsd:dateTime' fail the tests? What speaks against using them in the ontology for our purposes?

**Comment by zozlak** [comment]
> Why does a qualified restriction like ''has updated date' max 1 xsd:dateTime' fail the tests? What speaks against using them in the ontology for our purposes?

Because it either means you are repeating yourself (if acdh:hasUpdatedDate range is xsd:dateTime) or trying to do something nasty (change a property range for a particular class using a cardinality rule). In the first case just use unqualified restriction instead. In the second case you must create a new property with a desired range.

**Comment by zozlak** [comment]
> 3. Why does PID minting automation now has to be triggered by the user with a proper - empty string - property value? Before, the user had to submit something like 'create me' in the property. I am already thinking of the Metadata Editor here, where an additional query has to be added in the code and some visual element has to be included in the form, in order to properly allow the user to either not create a PID or automatically create one.

Before the PID was generated when achd:hasPid property with **any literal** was present. In practice it turned out someone started using "create me" and others followed and as "create me" is a perfectly valid any literal, it just worked fine :)

But during the process of cleaning the object/datatype properties mess we decided the acdh:hasPid should be an owl:DatatypeProperty which means its range has to be a literal. As a consequence the "any literal value triggers PID generation" rule made no sense any more (as it would now trigger PID minting on every resource metadata update) and we needed a new one.

I decided to narrow it to "empty literal value triggers PID generation" as an empty PID is for sure not a valid PID but honestly we can agree on any other single value (like "create me") or we can assume a valid PID must be an URL and if it's not, it should be generated (which also covers the "create me" value). Just whatever we decide upon, it should be denoted in the ontology in the acdh:hasPid property description.

**Comment by zozlak** [comment]
ad 2 you can reintroduce cardinalities, I will just adjust the doorkeeper (every task is better than cleaning AkSearch) ;) .

**Comment by zozlak** [comment]
> 1. Are there any objections from the technical point of view to remove it from the class Collection

No, there are no objections.

**Comment by bellerophons-pegasus** [comment]
ad 4: I see. Yes, the qualified restrictions were indeed some kind of repetition. Although now when adding an unqualified restriction via Protege the range is set to 'rdfs:Literal' ... I guess it is either that or the other... no optimal solution

**Comment by zozlak** [comment]
Displaying unqualified restriction range is a Protege convention which I personally find a little weird (because on the OWL level unqualified restrictions just don't have range or, if we really want to think about them in that way, inherit range from the property). And as we a) can't adjust Protege behavior b) at the end of a day wont a proper OWL, I would ask you to get used to this Protege convention.

**Comment by bellerophons-pegasus** [comment]
> I decided to narrow it to "empty literal value triggers PID generation" as an empty PID is for sure not a valid PID but honestly we can agree on any other single value (like "create me") or we can assume a valid PID must be an URL and if it's not, it should be generated (which also covers the "create me" value). Just whatever we decide upon, it should be denoted in the ontology in the acdh:hasPid property description.

Lets go this way: A new Handle will be created if the identifier provided equals 'create'. (added this into the description)

**Comment by zozlak** [comment]
Settled

**Comment by bellerophons-pegasus** [comment]
Last question regards the automatic checks. 
Currently I get two error types:
* restriction _:genid25 for class https://vocabs.acdh.oeaw.ac.at/schema#Collection and property https://vocabs.acdh.oeaw.ac.at/schema#hasNumberOfItems is not needed as the property is marked as automatically managed one
--> with nr2. cardinalities should now not be a problem; instead of an error this could be a warning or information
* restriction _:genid49 for class https://vocabs.acdh.oeaw.ac.at/schema#RepoObject and property https://vocabs.acdh.oeaw.ac.at/schema#hasHosting has min cardinality 1 which means its default value of https://id.acdh.oeaw.ac.at/arche will be never used
--> this is similar to the cardinality thing (i.e. the ontology documents which values have to be present at the end) and should also just be a warning or so

**Comment by zozlak** [comment]
Yes, you are right, the check script should be adjusted for what we agreed upon in 2.
So please just ignore these errors.
